---
kind: pipeline
type: docker
name: rebase

platform:
  arch: amd64
  os: linux

trigger:
  event:
    - cron
  cron:
    - weekly

steps:
- name: rebase-upstream
  image: alpine/git
  commands:
  - git remote add upstream https://github.com/Aircoookie/WLED.git
  - git fetch upstream
  - git checkout main
  - git rebase upstream/main
  # Push the rebased branch to your origin repository
  - |
    if [ $? -eq 0 ]; then
      echo "Rebase successful. Pushing changes."
      git push origin main --force-with-lease
      # Create a new tag based on the current date (e.g., vYYYYMMDD)
      TAG="v$(date +%Y%m%d)"
      echo "Creating new tag: $TAG"
      git tag -a "$TAG" -m "Automated tag for release on $(date)"
      git push origin "$TAG"
    else
      echo "Rebase failed. Please resolve conflicts."
    fi
- name: discord_notification_rebase_success
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_secret
    message: >
      ✅ Weekly WLED rebase completed successfully!
      
      🔄 Rebased from upstream and created new tag: ${TAG}
      📅 Date: $(date)
  when:
    status:
      - success

- name: discord_notification_rebase_failure
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_secret
    message: >
      ❌ Weekly WLED rebase failed!
      
      🔄 There might be conflicts that need manual resolution.
      🛠️ Check the build logs: https://ci.jallier.xyz/jallier/wled/${DRONE_BUILD_NUMBER}
      📅 Date: $(date)
  when:
    status:
      - failure

---
kind: pipeline
type: docker
name: release

platform:
  arch: amd64
  os: linux

trigger:
  event:
    - tag

steps:
- name: Build WLED
  image: node:20-alpine
  commands:
    # Setup Node.js dependencies
    - npm ci
    - npm run build
    
    # Install Python and PlatformIO dependencies
    - apk add --no-cache python3 py3-pip git
    # - python3 -m pip install --upgrade pip
    # - python3 -m pip install platformio
    
    # Verify installations
    - node --version
    - python3 --version
    - pio --version
    
    # Build with PlatformIO
    - python3 -m pip install -r requirements.txt
    - pio run -e esp32dev

- name: gitea_release
  image: plugins/gitea-release
  settings:
    api_key: 
      from_secret: gitea_release_key
    base_url: https://git.jallier.xyz
    files: build_output/release/*.bin

- name: discord_notification_success
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_secret
    message: >
      ✅ New WLED release deployed successfully!
      
      📦 Version: ${DRONE_TAG}
      🔗 Download: https://git.jallier.xyz/jallier/wled/releases/tag/${DRONE_TAG}
  when:
    status:
      - success

- name: discord_notification_failure
  image: appleboy/drone-discord
  settings:
    webhook_id:
      from_secret: discord_webhook_id
    webhook_token:
      from_secret: discord_webhook_secret
    message: >
      ❌ WLED release build failed!
      
      📦 Version: ${DRONE_TAG}
      🛠️ Check the build logs: https://ci.jallier.xyz/jallier/wled/${DRONE_BUILD_NUMBER}
  when:
    status:
      - failure
